// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApiWeb.Models;

namespace MyApiWeb.Migrations
{
    [DbContext(typeof(AllDBContext))]
    [Migration("20201204163900_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyApiWeb.Models.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cover")
                        .HasColumnName("cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnName("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .HasColumnName("developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnName("genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform_used")
                        .HasColumnName("platform_used")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platforms")
                        .HasColumnName("platforms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnName("publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release_date")
                        .HasColumnName("release_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("UsersId")
                        .HasColumnName("usersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cover = "https://localhost:5001/resources/images/games/gtav.jpg",
                            Desc = "GTA V",
                            Developer = "Rockstar North",
                            Genre = "Action and Adventure",
                            Platform_used = "PC",
                            Platforms = "PS3,X360,PS3,XONE,PS4,PC,PS5,XSERIES X|S",
                            Publisher = "Rockstar Games",
                            Release_date = new DateTime(2017, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "GTA V",
                            UsersId = 1
                        });
                });

            modelBuilder.Entity("MyApiWeb.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnName("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnName("cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .HasColumnName("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnName("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("UsersId")
                        .HasColumnName("usersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(429),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/1",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: yellow;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 1",
                            UsersId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(2733),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/2",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: orange;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 2",
                            UsersId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(2775),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/3",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: lightblue;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 3",
                            UsersId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(2777),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/4",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: orange;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 4",
                            UsersId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(2778),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/5",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: yellow;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 5",
                            UsersId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Exemplo",
                            Cover = "assets/images/cover.jpg",
                            Date = new DateTime(2020, 12, 4, 16, 39, 0, 457, DateTimeKind.Utc).AddTicks(2779),
                            Desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.",
                            Source = "/news/6",
                            Text = "<p class='t-justify'>Lorem ipsum dolor sit amet, <b style='background-color: orange;'>consectetur adipiscing elit</b>. Suspendisse lobortis vitae elit id sagittis. Integer maximus leo in dapibus feugiat. Duis nulla orci, consequat in lobortis vel, condimentum vel turpis. Morbi quis tincidunt enim. Nunc finibus mi felis. Sed lobortis ornare dui, sit amet consequat felis. Suspendisse id orci accumsan, tincidunt quam ultrices, fringilla turpis.</p><p>Youtube video: </p><iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/azdwsXLmrHE' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
                            Title = "Noticia 6",
                            UsersId = 1
                        });
                });

            modelBuilder.Entity("MyApiWeb.Models.RadiosList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RadioImage")
                        .HasColumnName("radioimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioSrc")
                        .IsRequired()
                        .HasColumnName("radiosrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioTitle")
                        .IsRequired()
                        .HasColumnName("radiotitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RadiosList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RadioImage = "https://localhost:5001/resources/images/radios/m80.jpg",
                            RadioSrc = "http://mcrscast.mcr.iol.pt/m80",
                            RadioTitle = "M80"
                        });
                });

            modelBuilder.Entity("MyApiWeb.Models.SaveGames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("File_img")
                        .HasColumnName("file_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_url")
                        .HasColumnName("file_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesId")
                        .HasColumnName("gamesId")
                        .HasColumnType("int");

                    b.Property<bool>("Is_req_to_100")
                        .HasColumnName("is_req_to_100")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Type_medal")
                        .HasColumnName("type_medal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersId")
                        .HasColumnName("usersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SaveGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            File_img = "https://localhost:5001/resources/images/games/gtav.jpg",
                            File_url = "https://gtasnp.com/v-prologue",
                            GamesId = 1,
                            Is_req_to_100 = true,
                            Title = "Prologue",
                            Type_medal = "Gold",
                            UsersId = 1
                        });
                });

            modelBuilder.Entity("MyApiWeb.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnName("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnName("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "luis@local.loc",
                            FirstName = "Luis",
                            Image = "https://localhost:5001/resources/images/luis.jpg",
                            LastName = "Carvalho",
                            Password = "$2a$11$MBdIjKpMNKvW3TTaQ0rhPOfAsTmpesa1Lt718Vg4ozGhJJEq5YO.S",
                            Role = "admin",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imx1aXMiLCJqdGkiOiI1ZDZiNDg4MS1mM2I4LTRkMjQtYThlYy1kZDQ1ZmNkZTZlMTciLCJleHAiOjE2MDc3MDQ3MzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.eJN2qSRmTDlHxgUJVWGe9UyXJ9EQHpUFdgeoZyFcNk8",
                            Username = "luis"
                        },
                        new
                        {
                            Id = 2,
                            Email = "guest@local.loc",
                            FirstName = "Guest",
                            Image = "https://localhost:5001/resources/images/guest.png",
                            LastName = "G",
                            Password = "$2a$11$XIFuKvD/OTKfMoZpqan3Wui8m6P8gPqP0EUdleAXjy8tA5NyTXFPS",
                            Role = "guest",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imd1ZXN0IiwianRpIjoiMGVhYjYyOTEtN2Q2NS00NjkyLTg2NjgtZjk1Y2I5MjhlNWNmIiwiZXhwIjoxNjA3NzA0NzM5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSJ9.8jucFIGU8B-pzFXEohkE660m76T8hhH7kdUkInZI20k",
                            Username = "guest"
                        },
                        new
                        {
                            Id = 3,
                            Email = "goku@local.loc",
                            FirstName = "Son",
                            Image = "https://localhost:5001/resources/images/goku.png",
                            LastName = "Goku",
                            Password = "$2a$11$dqf7gh6L8MlTFphbreDLBelVDD82UEg3r6P1mvpyka/mE.BlIkCpC",
                            Role = "user",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imdva3UiLCJqdGkiOiJmNDk2NTE1My01ZWRkLTRjODAtYTJmYS1iYzZiN2QzN2M4MmEiLCJleHAiOjE2MDc3MDQ3MzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.vYzL2yT-l5n5HEcYGRQC91ExAzTopGLXAQMWkZprF1M",
                            Username = "goku"
                        },
                        new
                        {
                            Id = 4,
                            Email = "danny_phantom@local.loc",
                            FirstName = "Danny",
                            Image = "https://localhost:5001/resources/images/danny.png",
                            LastName = "Phantom",
                            Password = "$2a$11$fPaEnzaegVBH.5mnk.gEU.zYGVuaLFwuscQK7kWVcgIfgD7SPGluS",
                            Role = "user",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRhbm55X3BoYW50b20iLCJqdGkiOiJiNDQwZDZmYi1lMGI1LTQ1MWItYWFhZi0zZDEzYTFlYzU1MzciLCJleHAiOjE2MDc3MDQ3MzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.oTHERFsetwW9sSczzrhv4INUS66PrEGzVEQmvyEqQ1U",
                            Username = "danny_phantom"
                        },
                        new
                        {
                            Id = 5,
                            Email = "jimmy_neutron@local.loc",
                            FirstName = "Jimmy",
                            Image = "https://localhost:5001/resources/images/jimmy.jpg",
                            LastName = "Neutron",
                            Password = "$2a$11$Lm3jU34IOFLah.i16OfHZuqAK2sQqE2ewKGNFS/JMOZ0yY9lOqcHi",
                            Role = "user",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImppbW15X25ldXRyb24iLCJqdGkiOiI1NGU2NTdmYy1lZTI5LTQ4YzktYWM0ZS0yYTQ5NWJiN2RiOTYiLCJleHAiOjE2MDc3MDQ3MzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.6Aag7e9UKaxVSWRWoGQL-hxBcJHKa-z55SZe75IjezM",
                            Username = "jimmy_neutron"
                        },
                        new
                        {
                            Id = 6,
                            Email = "timmy_turner@local.loc",
                            FirstName = "Timmy",
                            Image = "https://localhost:5001/resources/images/timmy.png",
                            LastName = "Turner",
                            Password = "$2a$11$XbZ.RL7IvfFk82LEVcEC..7GwYbDrEI2O1/xztSo3E4637B0N1cM2",
                            Role = "user",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRpbW15X3R1cm5lciIsImp0aSI6IjBiOWQ2MTliLTAwYmQtNGExOC1hYmRiLTJhNjY5YTRhMjI4MCIsImV4cCI6MTYwNzcwNDczOSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEifQ.GCjRGOsc8i3oHFswy2b5-v76QI3PDHpotNce7Y1F0Pc",
                            Username = "timmy_turner"
                        },
                        new
                        {
                            Id = 7,
                            Email = "iron_man@local.loc",
                            FirstName = "Iron",
                            Image = "https://localhost:5001/resources/images/ironman.jpg",
                            LastName = "Man",
                            Password = "$2a$11$VikNw3yntQ9Hi1nHxFgx0eEnzGYGsu8bDD970Gl.ic4YwmyASU.3C",
                            Role = "user",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imlyb25tYW4iLCJqdGkiOiIwYjUwMDAzYy04Mzk0LTQyOTEtYmM2Zi1hZjNkYWNkYjA3MTkiLCJleHAiOjE2MDc3MDQ3MzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.0XHyqsKZE9xMAvC5vo60dlCghJ5eUPCqUwXr3NmoCNc",
                            Username = "ironman"
                        });
                });

            modelBuilder.Entity("MyApiWeb.Models.Videos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnName("src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Src = "https://localhost:5001/resources/videos/v1.mp4",
                            Type = "video/mp4"
                        },
                        new
                        {
                            Id = 2,
                            Src = "https://localhost:5001/resources/videos/v2.mp4",
                            Type = "video/mp4"
                        },
                        new
                        {
                            Id = 3,
                            Src = "https://localhost:5001/resources/videos/v3.mp4",
                            Type = "video/mp4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
